language: python

python:
  - 3.9.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "tianfan"
  env: "tianfan-dev"
  bucket_name: "elasticbeanstalk-us-east-1-891377257918"
  on:
    branch: main 


          