language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

# script:
#   - black --check .
#   - flake8 .
#   - python manage.py migrate
#   - coverage run manage.py test
#   - coverage report

# after_script:
#   - coveralls


install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - python manage.py migrate
  - python manage.py test
  - coverage run manage.py test  
  - coverage report  
after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "tianfan"
  env: "tianfan-dev"
  bucket_name: "elasticbeanstalk-us-east-1-891377257918"
  on:
    branch: main 


          